name: "Cloudflare Publish"
description: "Publish a static site to cloudflare using wrangler"

inputs:
  ACCOUNT_ID:
    description: "The account-id that has been registered at cloudflare"
    required: true
  BRANCH_NAME:
    description: "Branch name of this publication, special branches trigger live release..."
    required: true
  CF_WRANGLER_TOKEN:
    description: "The secret token created on cloudflare"
    required: true
  COMMIT_HASH:
    description: "Commit hash (short) of this publication, an easy way to match your publication back to your commit"
    required: true
  DIST_NAME:
    description: "Name of the artifact to download"
    required: true
  PROJECT_NAME:
    description: "The cloudflare registered project name"
    required: true

outputs:
  WRANGLER_OUT:
    description: "The stdout logged from the wrangler action that was running"
    value: ${{ steps.wrangler.outputs.command-output }}
  CLOUDFLARE_URL:
    description: "The URL of wranglers publication"
    value: ${{ steps.url.outputs.CLOUDFLARE_URL }}

runs:
  using: "composite"
  steps:
  - name: Download artifact
    uses: actions/download-artifact@v4
    with:
      name:  ${{ inputs.DIST_NAME }}
      path: output
  - name: Publish app
    uses: cloudflare/wrangler-action@v3
    id: wrangler
    with:
      apiToken: ${{ inputs.CF_WRANGLER_TOKEN }}
      accountId: ${{ inputs.ACCOUNT_ID }}
      command: pages deploy output --project-name ${{ inputs.PROJECT_NAME }} --branch ${{ inputs.BRANCH_NAME }} --commit-hash ${{ inputs.COMMIT_HASH }}
  - name: Report output
    shell: bash
    run: echo "${{ steps.wrangler.outputs.command-output }}" | tail -n 3 >> $GITHUB_STEP_SUMMARY
  - name: Log URL
    id: url
    shell: bash
    run: echo "CLOUDFLARE_URL=$(echo '${{ steps.wrangler.outputs.command-output }}' | tail -n 10 | grep -Eo 'https?://[^ >]+' | head -1)" >> $GITHUB_OUTPUT
