name: "Cloudflare Publish"
description: "Publish a static site to cloudflare using wrangler"

inputs:
  ACCOUNT_ID:
    description: "The account-id that has been registered at cloudflare"
    required: true
  BRANCH_NAME:
    description: "Branch name of this publication, special branches trigger live release..."
    required: true
  CF_WRANGLER_TOKEN:
    description: "The secret token created on cloudflare"
    required: true
  COMMIT_HASH:
    description: "Commit hash (short) of this publication, an easy way to match your publication back to your commit"
    required: true
  DIST_NAME:
    description: "Name of the artifact to download"
    required: true
  PROJECT_NAME:
    description: "The cloudflare registered project name"
    required: true

runs:
  using: "composite"
  steps:
  - name: Download artifact
    uses: actions/download-artifact@v4
    with:
      name:  ${{ inputs.DIST_NAME }}
      path: output
  - name: Publish app
    uses: cloudflare/wrangler-action@v3
    with:
      apiToken: ${{ inputs.CF_WRANGLER_TOKEN }}
      accountId: ${{ inputs.ACCOUNT_ID }}
      command: pages deploy output --project-name ${{ inputs.PROJECT_NAME }} --branch ${{ inputs.BRANCH_NAME }} --commit-hash ${{ inputs.COMMIT_HASH }} | tee -a output.log
  - name: Report output
    shell: bash
    run: tail -n 3 output.log >> $GITHUB_STEP_SUMMARY
