name: "aws s3 bucket"
description: "push to aws s3 bucket"

inputs:
  PACKAGE_NAME:
    required: true
    description: "the name of the package you want push it to aws s3 bucket"
  BUCKET_NAME:
    required: true
    description: "the name of the aws s3 bucket"

runs:
  using: "composite"
  steps:
    -  uses: actions/checkout@v3
      
    - name: push to S3
      shell: bash
      run: |
        aws s3 sync ./${{ inputs.PACKAGE_NAME }} s3://${{ inputs.BUCKET_NAME }}/${{ inputs.PACKAGE_NAME }}
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}