name: "Node CI"
description: "Basic NodeJS CI"
inputs:
  NPM_REGISTRY_TOKEN:
    required: true
    description: "Your personal access token - PAT"
  NODE_VERSION:
    required: false
    default: "0"
    description: "The node version you would like to test"
  NODE_CACHE:
    required: false
    default: 'disabled'
    description: "Use caching on node-setup to reduce build time"
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - name: Use Node.js - ${{ inputs.NODE_VERSION }}
      if: ${{ inputs.NODE_VERSION != '0' }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.NODE_VERSION }}
      env:
        NPM_TOKEN: ${{ inputs.NPM_REGISTRY_TOKEN }}
    - name: Use Node.js Own version
      if: ${{ inputs.NODE_VERSION == '0' }}
      uses: actions/setup-node@v3
      with:
        node-version-file: '.nvmrc'
        cache:  ${{ inputs.NODE_CACHE }}
      env:
        NPM_TOKEN: ${{ inputs.NPM_REGISTRY_TOKEN }}
    - name: npm install, build, and test
      run: |
        npm ci
        npm run vulnerabilities
        npm run lint:report
        npm run cpd
        npm test
      shell: bash
      env:
        CI: "true"
        NPM_TOKEN: ${{ inputs.NPM_REGISTRY_TOKEN }}
