name: "Node Publish"
description: "Publish NodeJS package"
inputs:
  NPM_REGISTRY_TOKEN:
    required: true
    description: "Your personal access token - PAT"
  NODE_CACHE:
    required: false
    default: ""
    description: "Set NODE_CACHE to 'npm' to enabled cached dependencies"
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Use Node.js Own version
      uses: actions/setup-node@v4
      with:
        node-version-file: ".nvmrc"
        cache: ${{ inputs.NODE_CACHE }}
      env:
        NPM_TOKEN: ${{ inputs.NPM_REGISTRY_TOKEN }}
    - name: npm publish
      run: |
        npm ci --production
        npm publish
      shell: bash
      env:
        CI: "true"
        NPM_TOKEN: ${{ inputs.NPM_REGISTRY_TOKEN }}
