name: "Node Publish"
description: "Publish NodeJS package"
inputs:
  NPM_REGISTRY_TOKEN:
    required: true
    description: "Your personal access token - PAT"
  NODE_CACHE:
    required: false
    default: 'disabled'
    description: "Use caching on node-setup to reduce build time"
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - name: Use Node.js Own version
      uses: actions/setup-node@v3
      with:
        node-version-file: '.nvmrc'
        cache:  ${{ inputs.NODE_CACHE }}
      env:
        NPM_TOKEN: ${{ inputs.NPM_REGISTRY_TOKEN }}
    - name: npm publish
      run: |
        npm ci --production
        npm publish
      shell: bash
      env:
        CI: "true"
        NPM_TOKEN: ${{ inputs.NPM_REGISTRY_TOKEN }}
